# Generated by Django 3.1.3 on 2020-11-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='genre',
            field=models.CharField(default='Racing', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='games',
            name='violence',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
